name: Fernando Martinez Marco
description: Naval Architect | AI Architect | Senior Surveyor
avatar: https://github.com/fmmarco29.png

footer-links:
  github: fmmarco29
  linkedin: fmmarco29 # Asegúrate de que este sea tu usuario real de LinkedIn
  email: tu-correo@ejemplo.com

url: "https://fmmarco29.github.io"
baseurl: "" # Déjalo vacío para que cargue en la raíz
